default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: OCR_tickets_development

test:
  <<: *default
  database: OCR_tickets_test

production:
  <<: *default
  database: OCR_tickets_production
